name: hello

on: [push]

jobs:
  jsHello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: u0324020/actions-composition-hello@v2
      id: foo
      with:
        who-to-greet: 'Jane'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
